name: Update yt-dlp

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-yt-dlp:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      -
        name: Update yt-dlp
        run: |
          pip install pipenv
          pipenv sync
          VER=`pipenv run pip list -o | awk '$1 == "yt-dlp" {print $3}'`
          if [ -n "$VER" ]; then
            pipenv update --selective-upgrade yt-dlp
            git config --global user.email "updater@metube"
            git config --global user.name "AutoUpdater"
            git commit -m 'upgraded yt-dlp' Pipfile.lock
            git push
          fi
